### ISSUE TITLE
"vendor/brcm/rpi4/rpi4-vendor.mk" does not exist.

### ISSUE THREAD

**Issue by andersling** [maxwen/android_device_brcm_rpi4#4]
Hi,thanks for your greate effort!
  But when i finished sync the whole tree with serveral hours, when I run the LUNCH  command:

You're building on Linux

Lunch menu... pick a combo:
     1. aosp_arm-eng
     2. aosp_arm64-eng
     3. aosp_x86-eng
     4. aosp_x86_64-eng
     5. omni_emulator-userdebug
     6. omni_rpi4-userdebug

Which would you like? [aosp_arm-eng] 6
device/brcm/rpi4/device.mk:179: error: _nic.PRODUCTS.[[device/brcm/rpi4/omni_rpi4.mk]]: "vendor/brcm/rpi4/rpi4-vendor.mk" does not exist.
19:57:18 dumpvars failed with: exit status 1
WARNING: Trying to fetch a device that's already there
Traceback (most recent call last):
  File "vendor/omni/build/tools/roomservice.py", line 417, in <module>
    fetch_device(device)
  File "vendor/omni/build/tools/roomservice.py", line 385, in fetch_device
    git_data = search_gerrit_for_device(device)
  File "vendor/omni/build/tools/roomservice.py", line 81, in search_gerrit_for_device
    device_data = check_repo_exists(git_data, device)
  File "vendor/omni/build/tools/roomservice.py", line 58, in check_repo_exists
    "exiting roomservice".format(device=device))
Exception: rpi4 not found,exiting roomservice
device/brcm/rpi4/device.mk:179: error: _nic.PRODUCTS.[[device/brcm/rpi4/omni_rpi4.mk]]: "vendor/brcm/rpi4/rpi4-vendor.mk" does not exist.
19:57:22 dumpvars failed with: exit status 1

** Don't have a product spec for: 'omni_rpi4'
** Do you have the right repo manifest?

------------------------------------------------------------------
would you do me a favor to give me some tips to solve it?sir!

Thanks!

**Comment by amsurana** [comment]
@andersling Looks like we are in same situation.
I commented this line of code and moved on. 
In fact, I have also commented out `DeviceParts` from `device.mk`. It might break the build as well.

**Comment by changxiangzhong** [comment]
Same here.

**Comment by changxiangzhong** [comment]
Here's my history. I've encountered the same issue in 2022. The symptom is `${omni_rpi_root}/.repo/local_manifests/roomservice.xml` does not exist. So I have manually clone the *proprietary_vendor_brcm* project. And did it again. I've no idea why it happens and how it's worked around. Good luck
```shell
 2006  mkdir aosp-omni-rpi4
 2007  cd aosp-omni-rpi4/
 2008  repo init -u git://github.com/omnirom/android.git -b android-11
 2009  mkdir .repo/local_manifests
 2010  ls
 2011  wget https://raw.githubusercontent.com/maxwen/android_device_brcm_rpi4/android-11/repo/local_manifest.xml -P .repo/local_manifests/
 2012  cat .repo/local_manifests/local_manifest.xml
 2013  repo sync
 2014  export ROM_BUILDTYPE=MICROG
 2015  export TEMPORARY_DISABLE_PATH_RESTRICTIONS=true
 2016  export ROM_BUILDTYPE=MICROG
 2017  export ALLOW_MISSING_DEPENDENCIES=true
 2018  export PRODUCT_EXCLUDE_EXTRA_PACKAGES=true
 2019  source build/envsetup.sh
 2020  echo ${PRODUCT_EXCLUDE_EXTRA_PACKAGES}
 2021  source build/envsetup.sh
 2022  lunch omni_rpi4-userdebug
 2023  git clone https://github.com/maxwen/proprietary_vendor_brcm -b android-11 vendor/brcm/
 2024  lunch omni_rpi4-userdebug
 2025  rm -rf vendor/brcm/rpi4/
 2026  repo sync --force-sync
 2027  lunch omni_rpi4-userdebug
 2028  make -j 12
```
